import { createMuiTheme } from '@material-ui/core/styles';
import themePalette from '../palette';

/*
 * When building the actual theme in DolomiteTheme.js, overrides will be imported
 * and those overrides will be using colors generated by a base palette (see palette.js)
 * and then enhanced by `createMuiTheme.` The problem is that in order for the enhanced
 * palette to be available in the overrides imported in the overrides.js file, an MuiTheme
 * must be already created. In order to subvert a feedback loop, ThemeColors creates an
 * MuiTheme with ONLY the colors (no overrides) and makes the generated enhanced palette
 * available to the overrides.
 */
function getThemePalette() {
  if (window.theme == null) window.theme = createMuiTheme({ palette: themePalette });
  return window.theme.palette;
}

export default getThemePalette();
